FROM debian:bookworm AS downloader

ARG KERNEL_VERSION=3.0.1

# # Install dependencies
RUN apt-get update && \
    apt-get install -y wget libssl-dev ca-certificates xz-utils

WORKDIR /usr/src

RUN wget https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_VERSION%%.*}.x/linux-${KERNEL_VERSION}.tar.xz && \
    tar -xf linux-${KERNEL_VERSION}.tar.xz && rm linux-${KERNEL_VERSION}.tar.xz

FROM debian:squeeze AS builder

ARG KERNEL_VERSION=3.0.1

COPY --from=downloader /usr/src/linux-${KERNEL_VERSION} /usr/src/linux-${KERNEL_VERSION}

RUN \
    sed -i 's|http://httpredir.debian.org/debian|http://archive.debian.org/debian|' /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until false;' > /etc/apt/apt.conf.d/10no--check-valid && \
    echo 'Acquire::AllowInsecureRepositories "true";' > /etc/apt/apt.conf.d/90insecure && \
    echo 'APT::Get::AllowUnauthenticated "true";' >> /etc/apt/apt.conf.d/90insecure


# # Install dependencies
RUN apt-get update -y; \
    apt-get install --allow-unauthenticated -y gcc make libc6-dev rsync

# WORKDIR /usr/src

# wget https://cdn.kernel.org/pub/linux/kernel/v${KERNEL_VERSION%%.*}.x/linux-${KERNEL_VERSION}.tar.xz && \
#RUN    tar -xf linux-${KERNEL_VERSION}.tar.xz && rm linux-${KERNEL_VERSION}.tar.xz

WORKDIR /usr/src/linux-${KERNEL_VERSION}

RUN mkdir -p /build && \
    for arch in \
        alpha \
        arm \
        arm64 \
        csky \
        hexagon \
        loongarch \
        m68k \
        mips \
        powerpc \
        riscv \
        s390 \
        sh \
        sparc \
        x86; do \
        if [ -d arch/$arch ]; then \
            echo "Building headers for $arch..." && \
            make ARCH=$arch headers_install INSTALL_HDR_PATH=/build/$arch; \
        fi \
    done

FROM scratch AS export
COPY --from=builder /build /build
COPY --from=builder /bin/true /bin/true
